name: Send Daily Message

on:
  schedule:
    - cron: '0 8 * * *'  # كل يوم الساعة 8 صباحًا بتوقيت UTC
  workflow_dispatch:     # لتشغيله يدويًا من GitHub

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run bot script
      run: python bot.py
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
